name: Issue Trigger

on:
  issues:
    types: [edited, labeled, unlabeled]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  dewhale-trigger:
    runs-on: ubuntu-latest
    name: Characters Trigger
    if: ${{ !contains(github.event.comment.body, '[Dewhale]') && github.event.comment.user.type != 'bot'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: trigger
        env:
          # auto set by GitHub, details in
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTOR: ${{ github.actor }}
          BRANCH: ${{ github.head_ref }}
          DEWHALE_CONFIG: ${{ secrets.DEWHALE_CONFIG }}
        run: |
          echo "${{ secrets.DEWHALE_CONFIG }}" > .env
          deno run -A src/entry.ts
